/** * click.js: contains functions regarding clicks on htlivesight.html elements. */ htlivesight.Click = {/*		Test: function (event) {			try {				var url = Components.classes["@mozilla.org/network/standard-url;1"].createInstance();				url = url.QueryInterface(Components.interfaces.nsIURL);				url.spec = htlivesightEnv.contentPath+"sound/wav.wav";				var sample = Components.classes["@mozilla.org/sound;1"].createInstance( );				sample = sample.QueryInterface(Components.interfaces.nsISound);				sample.play(url);				alert("Test!!");			} catch(e) {				htlivesight.Log.warn("Click.Test:" + e);			}		},*/				MuteAll: function (event) {			if (!htlivesight.prefs){				htlivesight.prefs = htlivesight.Preferences.get();			}			if(document.getElementById("chkSound").checked) {				document.getElementById("chkSoundOnlyOpened").disabled = true;				document.getElementById("chkSound").checked=false;				document.getElementById("muteAllImg").src="./img/sound_off.gif";				htlivesight.prefs.notification.sound = false;				htlivesightPrefs.setBool("notification.sound",htlivesight.prefs.notification.sound);			} else {				document.getElementById("chkSoundOnlyOpened").disabled = false;				document.getElementById("chkSound").checked=true;				var volume = $( "#volume_slider" ).slider( "option", "value" );				htlivesight.setvolume(volume);				//if(volume > 0 && volume <= 33)	$("#muteAllImg").attr('src', "./img/sound_on.gif");	  		//if(volume > 33 && volume <= 66)	$("#muteAllImg").attr('src', "./img/sound_on_1.gif");	  		//if(volume > 66)	$("#muteAllImg").attr('src', "./img/sound_on_2.gif");				//document.getElementById("muteAllImg").src="./img/sound_on.gif";				htlivesight.prefs.notification.sound = true;				htlivesightPrefs.setBool("notification.sound",htlivesight.prefs.notification.sound);			};		},		PlayPauseSwitcher: function (event) {			label = document.getElementById("playPauseButton").value;			if(label == "■"){				label = "▶";				htlivesight.Live.relivePlay= false;				 if('speechSynthesis' in window){window.speechSynthesis.pause();};			}else if(label == "▶"){				label = "■";				htlivesight.Live.relivePlay= true;				if('speechSynthesis' in window){window.speechSynthesis.resume();};			}			document.getElementById("playPauseButton").value= label;		},				GoToEnd: function (event) {			htlivesight.Live.addTime = 2000;			htlivesight.prefs.other.reLiveSpeed = 60;		},				SetReliveSpeed: function (event) {			htlivesight.prefs.other.reLiveSpeed = document.getElementById("reLiveSpeedPanel").value;		},		
		AddMatch: function (event) {			var matchId = parseInt(document.getElementById("boxaddmatch").value, 10);			var sourceSystem= document.getElementById("sourceSystem").value;			if (matchId) {				htlivesight.AddLiveMatch(matchId, sourceSystem);			}		},				Login: function (event) {			htlivesight.Login.teamId = document.getElementById("teamId").value;			var getMyDataAutomatically = document.getElementById("getMyDataAutomatically").checked;			if (htlivesight.Login.teamId == "" && !getMyDataAutomatically){				return;			};			htlivesight.getRecommendedServer();			$('#login-dialog').dialog("close"); 		},
		Logout: function (event) {			htlivesight.Logout();		},
		AddMatchByTeam: function (event) {			var teamId = parseInt(document.getElementById("boxaddmatch").value, 10);			if(teamId < 3400 && teamId > 3000) alert("Cannot add match by Team Id for National Teams/U21");			var sourceSystem = document.getElementById("sourceSystem").value;			var youth="False";			if ((sourceSystem=="youth")||(sourceSystem=="Youth")){youth="True";}			if(teamId) {				htlivesight.Matches.HTTPGetByTeam(teamId, youth, true);			}		},
		ClearLog: function() {			var logElement = document.getElementById("logbox");			logElement.setAttribute("value", "");		},
		window: function() {			var id=this.getAttribute("id").split("_");			htlivesight.DOM.window.set(id[1], id[2], htlivesight.DOM.mode[id[0]]);			if (id[0] === "close"){				htlivesight.DOM.closeMatchRelatedWindows(id[1]+"_"+id[2]);  		//	$("#home_team_formation_"+id[1]+"_"+id[2]+"_table").dialog("close");	  	//	$("#away_team_formation_"+id[1]+"_"+id[2]+"_table").dialog("close");		  //	$("#home_team_name_"+id[1]+"_"+id[2]+"_statistics").dialog("close");			 // $("#away_team_name_"+id[1]+"_"+id[2]+"_statistics").dialog("close");			}		},
		moveDown: function() {			var id=this.getAttribute("id").split("_");			var window = $("#live_"+id[1]+"_"+id[2]);			var next = window.nextAll(".live_match_shown:first");			console.log(next);			if(next){				console.log("moving down");				window.insertAfter(next);			}			//window.parentNode.insertBefore(window, next);			this.setAttribute("src", htlivesight.Image.window.down.OFF);			/*var id=this.getAttribute("id").split("_");			var window=document.getElementById("live_"+id[1]+"_"+id[2]);			var next=window.nextSibling;			console.log(next);			if (next != null && next.hidden == false && !next.class)				next = next.nextSibling;			console.log(next);			window.parentNode.insertBefore(window, next);			this.setAttribute("src", htlivesight.Image.window.down.OFF);*/		},
		moveUp: function() {			console.log("in moveUp");			var id = this.getAttribute("id").split("_");			console.log("id = " + id);			var window = $("#live_"+id[1]+"_"+id[2]);			console.log(window);			var prev = window.prevAll(".live_match_shown:first");			console.log(prev);			if(prev){				console.log("moving up");				window.insertBefore(prev);				console.log("moved up");			}			console.log("151");			this.setAttribute("src", htlivesight.Image.window.up.OFF);			console.log("153");			/*var id=this.getAttribute("id").split("_");			var window=document.getElementById("live_"+id[1]+"_"+id[2]);			var prev=window.previousSibling;			console.log(prev);			if(prev){				window.parentNode.insertBefore(window, prev);			}			this.setAttribute("src", htlivesight.Image.window.up.OFF);*/		},
		over: function() {			var id=this.getAttribute("id").split("_");			var windowmode=htlivesight.Match.List["_"+id[1]+"_"+id[2]].window.mode;			var mode = htlivesight.DOM.mode[id[0]];			if (mode == windowmode) return;			switch (mode) {			case htlivesight.DOM.mode.close:				this.setAttribute("src", htlivesight.Image.window.close.ON);				break;
			case htlivesight.DOM.mode.shade:				this.setAttribute("src", htlivesight.Image.window.shade.ON);				break;
			case htlivesight.DOM.mode.minimize:				this.setAttribute("src", htlivesight.Image.window.minimize.ON);				break;
			case htlivesight.DOM.mode.maximize:				this.setAttribute("src", htlivesight.Image.window.maximize.ON);				break;
			case htlivesight.DOM.mode.moveup:				this.setAttribute("src", htlivesight.Image.window.up.ON);				break;
			case htlivesight.DOM.mode.movedown:				this.setAttribute("src", htlivesight.Image.window.down.ON);				break;
			case htlivesight.DOM.mode.link:				this.setAttribute("src", htlivesight.Image.window.link.ON);				break;			}		},
		out: function() {			var id=this.getAttribute("id").split("_");			var windowmode=htlivesight.Match.List["_"+id[1]+"_"+id[2]].window.mode;			var mode = htlivesight.DOM.mode[id[0]];			if (mode == windowmode) return;			switch (mode) {			case htlivesight.DOM.mode.close:				this.setAttribute("src", htlivesight.Image.window.close.OFF);				break;
			case htlivesight.DOM.mode.shade:				this.setAttribute("src", htlivesight.Image.window.shade.OFF);				break;
			case htlivesight.DOM.mode.minimize:				this.setAttribute("src", htlivesight.Image.window.minimize.OFF);				break;
			case htlivesight.DOM.mode.maximize:				this.setAttribute("src", htlivesight.Image.window.maximize.OFF);				break;
			case htlivesight.DOM.mode.moveup:				this.setAttribute("src", htlivesight.Image.window.up.OFF);				break;
			case htlivesight.DOM.mode.movedown:				this.setAttribute("src", htlivesight.Image.window.down.OFF);				break;			case htlivesight.DOM.mode.link:				this.setAttribute("src", htlivesight.Image.window.link.OFF);				break;			}		},		tip: function() {			var id=this.getAttribute("id").split("_");			htlivesight.DOM.toggleTip(id[1], id[2]);		},
		link: function() {			var id=this.getAttribute("id").split("_");			htlivesight.DOM.toggleLink(id[id.length-2], id[id.length-1]);		},		sound: function() {			var id=this.getAttribute("id").split("_");			htlivesight.DOM.toggleSound(id[1], id[2]);		},		speech: function() {			var id=this.getAttribute("id").split("_");			htlivesight.DOM.toggleSpeech(id[1], id[2]);		},		ToggleMatch: function() {			var id = this.getAttribute("id").split("_");			htlivesight.DOM.toggleView(id[2], id[3]);		},
		DeleteMatch: function() {			var id = this.getAttribute("id").split("_");			htlivesight.DOM.deleteView(id[2], id[3]);			htlivesight.DOM.closeMatchRelatedWindows(id[2]+"_"+id[3]);			//$("#home_team_formation_"+id[2]+"_"+id[3]+"_table").dialog("close");  		//$("#away_team_formation_"+id[2]+"_"+id[3]+"_table").dialog("close");	  	//$("#home_team_name_"+id[2]+"_"+id[3]+"_statistics").dialog("close");		  //$("#away_team_name_"+id[2]+"_"+id[3]+"_statistics").dialog("close");		},
		addTeamToFriendsList: function(teamId, youth) {			htlivesight.Friends.add(teamId, youth);		},
		AddButtonListeners: function() {			var elem;			elem = document.getElementById("buttonAddTeam");			elem.addEventListener('command', htlivesight.Click.AddMatchByTeam, true);
			elem = document.getElementById("buttonAddMatch");			elem.addEventListener('command', htlivesight.Click.AddMatch, true);			elem = document.getElementById("button_login");			elem.addEventListener('command', htlivesight.Click.Login, true);		},
		winboxOpen: function() {			var name=this.id.split("_")[1];			htlivesight.winboxOpenByName(name);		},
		winboxShade: function() {			var name=this.id.split("_")[1];			htlivesight.winboxShadeByName(name);		},
		loginClose: function() {			document.getElementById('login-dialog').dialog = true;		},
		removeFriend: function() {			htlivesight.Friends.remove();		},
		addFriendMatch: function() {			htlivesight.Friends.addMatch(true);		},
		moveUpFriend: function() {			htlivesight.Friends.moveUp();		},
		moveDownFriend: function() {			htlivesight.Friends.moveDown();		},				openPlayerLink:function(element){			var classPlayer = element.className;			classPlayer= classPlayer.split(" ");			var playerIdYouth = classPlayer[0].split("_");			if(playerIdYouth[1]=="youth"){				window.open("https://www.hattrick.org/goto.ashx?path=/Club/Players/YouthPlayer.aspx?YouthPlayerID="+playerIdYouth[0]);			}else{				window.open("https://www.hattrick.org/goto.ashx?path=/Club/Players/Player.aspx?playerId="+playerIdYouth[0]);			}		},				openTeamLink:function(teamId, sourceSystem){			if(htlivesight.Team.IsNationalTeam(teamId)){				window.open("https://www.hattrick.org/goto.ashx?path=/Club/NationalTeam/NationalTeam.aspx?teamId=" + teamId);				}else if(sourceSystem.toLowerCase() == 'youth'){				window.open("https://www.hattrick.org/goto.ashx?path=/Club/Youth/?YouthTeamID=" + teamId);				}else{				window.open("https://www.hattrick.org/goto.ashx?path=/Club/?TeamID=" + teamId);			}					},				getMyDataAutomatically: function() {			var checked  = document.getElementById("getMyDataAutomatically").checked;			if(checked){				$("#manualLoginFields").hide();			}else{				$("#manualLoginFields").show();			}		},};